//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvancePOTC_Ficha04
    {
        public AvancePOTC_Ficha04()
        {
            this.AvancePOTC_Ficha04Integrantes = new HashSet<AvancePOTC_Ficha04Integrantes>();
        }
    
        public int avanceid { get; set; }
    
        public virtual ICollection<AvancePOTC_Ficha04Integrantes> AvancePOTC_Ficha04Integrantes { get; set; }
        public virtual AvancePOTC AvancePOTC { get; set; }
    }
}
