//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvancePOTC_Ficha02
    {
        public int avanceid { get; set; }
        public string plataformatemas { get; set; }
        public Nullable<System.DateTime> plataformafechacreacion { get; set; }
        public Nullable<System.DateTime> plataformafechadisponible { get; set; }
        public Nullable<System.DateTime> plataformafechaultima { get; set; }
        public string plataformaresponsable { get; set; }
        public Nullable<byte> plataformanumeroentradas { get; set; }
        public Nullable<byte> plataformanumerocomentarios { get; set; }
        public Nullable<byte> disenosmsimagenes { get; set; }
        public Nullable<byte> disenosmstexto { get; set; }
        public Nullable<byte> disenosmsaudio { get; set; }
        public Nullable<byte> disenosmsvideo { get; set; }
        public Nullable<System.DateTime> disenosmsfechaelaboracion { get; set; }
        public Nullable<System.DateTime> disenosmsfechadifusion { get; set; }
        public string disenosmsdescripcion { get; set; }
        public Nullable<bool> produccionafiche { get; set; }
        public Nullable<bool> produccionposter { get; set; }
        public Nullable<bool> produccionlienzo { get; set; }
        public Nullable<bool> producciongigantografia { get; set; }
        public Nullable<bool> producciontriptico { get; set; }
        public Nullable<bool> produccionvolante { get; set; }
        public Nullable<bool> produccionjuegos { get; set; }
        public string produccionotro { get; set; }
        public Nullable<System.DateTime> produccionfechaelaboracion { get; set; }
        public Nullable<bool> produccionimpresion { get; set; }
        public string produccionejemplares { get; set; }
        public string producciondescripcion { get; set; }
        public Nullable<bool> difusionspotvideo { get; set; }
        public Nullable<bool> difusionspotaudio { get; set; }
        public string difusionspototro { get; set; }
        public string difusionmensaje { get; set; }
        public string difusionduracion { get; set; }
        public Nullable<System.DateTime> difusionfechaproduccion { get; set; }
        public string difusionlugarproduccion { get; set; }
        public string difusionresponsableproduccion { get; set; }
        public Nullable<System.DateTime> difusionfechaelaboracion1 { get; set; }
        public string difusiontitulo1 { get; set; }
        public Nullable<System.DateTime> difusionfechaelaboracion2 { get; set; }
        public string difusiontitulo2 { get; set; }
        public string difusionfrecuencianombre1 { get; set; }
        public Nullable<byte> difusionfrecuenciaveces1 { get; set; }
        public string difusionfrecuencianombre2 { get; set; }
        public Nullable<byte> difusionfrecuenciaveces2 { get; set; }
    
        public virtual AvancePOTC AvancePOTC { get; set; }
    }
}
