//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvancePOTC_Ficha06
    {
        public AvancePOTC_Ficha06()
        {
            this.AvancePOTC_Ficha06Integrantes = new HashSet<AvancePOTC_Ficha06Integrantes>();
        }
    
        public int avanceid { get; set; }
    
        public virtual ICollection<AvancePOTC_Ficha06Integrantes> AvancePOTC_Ficha06Integrantes { get; set; }
        public virtual AvancePOTC AvancePOTC { get; set; }
    }
}
