//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvancePOTC_Ficha03
    {
        public int avanceid { get; set; }
        public Nullable<byte> tiporeunion { get; set; }
        public string reunionotra { get; set; }
        public string reuniontema { get; set; }
        public string reunionlocal { get; set; }
        public Nullable<System.DateTime> reunionfecha { get; set; }
        public string reunionadministrador { get; set; }
        public string reunioncuerdo1 { get; set; }
        public string reunioncuerdo2 { get; set; }
        public string reunioncuerdo3 { get; set; }
        public string reunioncuerdo4 { get; set; }
        public string reunioncuerdo5 { get; set; }
        public Nullable<System.DateTime> fechaproxima { get; set; }
        public string reunionacomentarios { get; set; }
    
        public virtual AvancePOTC AvancePOTC { get; set; }
    }
}
