//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvancePOTC
    {
        public AvancePOTC()
        {
            this.AvancePOTC_Archivo = new HashSet<AvancePOTC_Archivo>();
        }
    
        public int id { get; set; }
        public int tareaid { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fechaingreso { get; set; }
        public int sectorid { get; set; }
        public int ejeintervencionid { get; set; }
        public int telecentroid { get; set; }
        public int regionid { get; set; }
        public System.DateTime fechainicio { get; set; }
        public System.DateTime fechafin { get; set; }
        public System.DateTime fechareporte { get; set; }
        public Nullable<int> promotorid { get; set; }
        public Nullable<bool> nodiscapacitados { get; set; }
        public Nullable<bool> discapacitados { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> poblacion01 { get; set; }
        public Nullable<bool> poblacion02 { get; set; }
        public Nullable<bool> poblacion03 { get; set; }
        public Nullable<bool> poblacion04 { get; set; }
        public Nullable<bool> poblacion05 { get; set; }
        public Nullable<bool> poblacion06 { get; set; }
        public Nullable<bool> poblacion07 { get; set; }
        public Nullable<bool> poblacion08 { get; set; }
        public Nullable<bool> poblacion09 { get; set; }
        public Nullable<bool> poblacion10 { get; set; }
        public Nullable<bool> poblacion11 { get; set; }
        public Nullable<bool> poblacion12 { get; set; }
        public Nullable<bool> poblacion13 { get; set; }
        public Nullable<bool> poblacion14 { get; set; }
        public Nullable<bool> poblacion15 { get; set; }
        public Nullable<bool> poblacion16 { get; set; }
        public string poblacionotro { get; set; }
        public Nullable<int> desaprobados { get; set; }
        public Nullable<int> retirados { get; set; }
        public Nullable<int> evaluacion { get; set; }
        public Nullable<int> certificados { get; set; }
        public Nullable<int> totalparticipantes { get; set; }
        public Nullable<int> horas { get; set; }
        public Nullable<decimal> productores { get; set; }
        public Nullable<decimal> noproductores { get; set; }
        public Nullable<int> rangoedad1 { get; set; }
        public Nullable<int> rangoedad2 { get; set; }
        public Nullable<int> rangoedad3 { get; set; }
        public Nullable<int> rangoedad4 { get; set; }
        public Nullable<bool> sustentoficha1 { get; set; }
        public Nullable<bool> sustentoficha2 { get; set; }
        public Nullable<bool> sustentoficha3 { get; set; }
        public Nullable<bool> sustentoficha4 { get; set; }
        public Nullable<bool> sustentoficha5 { get; set; }
        public Nullable<bool> sustentoficha6 { get; set; }
        public Nullable<bool> sustentovideos { get; set; }
        public string sustentootros { get; set; }
        public Nullable<int> participanteshombres { get; set; }
        public Nullable<int> participantesmujeres { get; set; }
        public string lugar { get; set; }
        public Nullable<decimal> lugarnumerohoras { get; set; }
        public Nullable<decimal> lugarcostohora { get; set; }
        public Nullable<int> difusionemisionesradio { get; set; }
        public Nullable<int> difusionemisionestv { get; set; }
        public Nullable<int> difusionemisionesprensa { get; set; }
        public Nullable<int> difusionsegundosradio { get; set; }
        public Nullable<int> difusionsegundostv { get; set; }
        public Nullable<int> difusionsegundosprensa { get; set; }
        public Nullable<decimal> difusioncostoradio { get; set; }
        public Nullable<decimal> difusioncostotv { get; set; }
        public Nullable<decimal> difusioncostoprensa { get; set; }
        public Nullable<int> voluntariosnumero { get; set; }
        public Nullable<decimal> voluntarioshoras { get; set; }
        public Nullable<decimal> voluntarioscostohora { get; set; }
        public Nullable<int> consultoresnumero { get; set; }
        public Nullable<decimal> consultoreshoras { get; set; }
        public Nullable<decimal> consultorescostohora { get; set; }
        public Nullable<int> asesoriahoras { get; set; }
        public Nullable<decimal> asesoriacostohora { get; set; }
        public Nullable<int> temporalid { get; set; }
        public Nullable<int> codigocapacitacion { get; set; }
        public bool aud_anulado { get; set; }
        public long aud_fechareg { get; set; }
        public string aud_usuarioreg { get; set; }
        public string aud_ipreg { get; set; }
        public long aud_fechamod { get; set; }
        public string aud_usuariomod { get; set; }
        public string aud_ipmod { get; set; }
        public decimal costototalalimentacion { get; set; }
        public decimal costototalmovilidad { get; set; }
    
        public virtual ICollection<AvancePOTC_Archivo> AvancePOTC_Archivo { get; set; }
        public virtual AvancePOTC_Ficha01 AvancePOTC_Ficha01 { get; set; }
        public virtual AvancePOTC_Ficha02 AvancePOTC_Ficha02 { get; set; }
        public virtual AvancePOTC_Ficha03 AvancePOTC_Ficha03 { get; set; }
        public virtual AvancePOTC_Ficha04 AvancePOTC_Ficha04 { get; set; }
        public virtual AvancePOTC_Ficha06 AvancePOTC_Ficha06 { get; set; }
        public virtual PlanOperativoTareaTC PlanOperativoTareaTC { get; set; }
    }
}
