//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvancePO
    {
        public AvancePO()
        {
            this.AvancePO_Archivo = new HashSet<AvancePO_Archivo>();
        }
    
        public int id { get; set; }
        public int metaid { get; set; }
        public System.DateTime fechainicio { get; set; }
        public System.DateTime fechafin { get; set; }
        public decimal monto { get; set; }
        public decimal cantidad { get; set; }
        public string observacion { get; set; }
    
        public virtual ICollection<AvancePO_Archivo> AvancePO_Archivo { get; set; }
        public virtual PlanOperativoMeta PlanOperativoMeta { get; set; }
    }
}
