//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        public Clase()
        {
            this.Participantes = new HashSet<Participantes>();
        }
    
        public int id { get; set; }
        public int sesionid { get; set; }
        public int listaid { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public decimal horas { get; set; }
        public string horainicio { get; set; }
        public string horafin { get; set; }
        public Nullable<decimal> horascalculadas { get; set; }
        public Nullable<int> minutoscalculados { get; set; }
    
        public virtual Sesion Sesion { get; set; }
        public virtual ICollection<Participantes> Participantes { get; set; }
    }
}
