//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcoLogicoTC
    {
        public MarcoLogicoTC()
        {
            this.PropositoMetasTC = new HashSet<PropositoMetasTC>();
            this.ResultadoTC = new HashSet<ResultadoTC>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public System.DateTime periodoinicio { get; set; }
        public System.DateTime periodofin { get; set; }
        public string fin { get; set; }
        public string proposito { get; set; }
        public string supuesto { get; set; }
        public string nombre { get; set; }
        public bool aud_anulado { get; set; }
        public long aud_fechareg { get; set; }
        public string aud_usuarioreg { get; set; }
        public string aud_ipreg { get; set; }
        public long aud_fechamod { get; set; }
        public string aud_usuariomod { get; set; }
        public string aud_ipmod { get; set; }
    
        public virtual ICollection<PropositoMetasTC> PropositoMetasTC { get; set; }
        public virtual ICollection<ResultadoTC> ResultadoTC { get; set; }
    }
}
