//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcoLogico
    {
        public MarcoLogico()
        {
            this.PropositoMetas = new HashSet<PropositoMetas>();
            this.Resultado = new HashSet<Resultado>();
        }
    
        public int id { get; set; }
        public int proyectoid { get; set; }
        public System.DateTime periodoinicio { get; set; }
        public System.DateTime periodofin { get; set; }
        public string fin { get; set; }
        public string codigo { get; set; }
        public string proposito { get; set; }
        public string supuesto { get; set; }
        public bool aud_anulado { get; set; }
        public long aud_fechareg { get; set; }
        public string aud_usuarioreg { get; set; }
        public string aud_ipreg { get; set; }
        public long aud_fechamod { get; set; }
        public string aud_usuariomod { get; set; }
        public string aud_ipmod { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        public virtual ICollection<PropositoMetas> PropositoMetas { get; set; }
        public virtual ICollection<Resultado> Resultado { get; set; }
    }
}
