//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMECEntities : DbContext
    {
        public SMECEntities()
            : base("name=SMECEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Inscripcion> Inscripcion { get; set; }
        public DbSet<ModuloArchivo> ModuloArchivo { get; set; }
        public DbSet<Modulos> Modulos { get; set; }
        public DbSet<Sesion> Sesion { get; set; }
        public DbSet<AvanceMLTC_Archivo> AvanceMLTC_Archivo { get; set; }
        public DbSet<AvancePO_Archivo> AvancePO_Archivo { get; set; }
        public DbSet<AvancePOTC_Archivo> AvancePOTC_Archivo { get; set; }
        public DbSet<AvancePropositoMetas_Archivo> AvancePropositoMetas_Archivo { get; set; }
        public DbSet<AvanceResultadoMetas_Archivo> AvanceResultadoMetas_Archivo { get; set; }
        public DbSet<Documento> Documento { get; set; }
        public DbSet<DocumentoArchivo> DocumentoArchivo { get; set; }
        public DbSet<PlanOperativoMetaArchivo> PlanOperativoMetaArchivo { get; set; }
        public DbSet<PlanOperativoTareaArchivoTC> PlanOperativoTareaArchivoTC { get; set; }
        public DbSet<PropositoMetaArchivo> PropositoMetaArchivo { get; set; }
        public DbSet<PropositoMetaArchivoTC> PropositoMetaArchivoTC { get; set; }
        public DbSet<ResultadoMetaArchivo> ResultadoMetaArchivo { get; set; }
        public DbSet<ResultadoMetaArchivoTC> ResultadoMetaArchivoTC { get; set; }
        public DbSet<AvancePropositoMetas> AvancePropositoMetas { get; set; }
        public DbSet<AvanceResultadoMetas> AvanceResultadoMetas { get; set; }
        public DbSet<Ubigeo> Ubigeo { get; set; }
        public DbSet<AvancePO> AvancePO { get; set; }
        public DbSet<AvancePOTC_Ficha06> AvancePOTC_Ficha06 { get; set; }
        public DbSet<MarcoLogico> MarcoLogico { get; set; }
        public DbSet<PlanOperativo> PlanOperativo { get; set; }
        public DbSet<PlanOperativoMeta> PlanOperativoMeta { get; set; }
        public DbSet<PlanOperativoMetaAnual> PlanOperativoMetaAnual { get; set; }
        public DbSet<PlanOperativoTareaMetaTC> PlanOperativoTareaMetaTC { get; set; }
        public DbSet<PlanOperativoTC> PlanOperativoTC { get; set; }
        public DbSet<PropositoMetas> PropositoMetas { get; set; }
        public DbSet<PropositoMetasTC> PropositoMetasTC { get; set; }
        public DbSet<Proyecto> Proyecto { get; set; }
        public DbSet<Resultado> Resultado { get; set; }
        public DbSet<ResultadoMetas> ResultadoMetas { get; set; }
        public DbSet<ResultadoMetasTC> ResultadoMetasTC { get; set; }
        public DbSet<ResultadoTC> ResultadoTC { get; set; }
        public DbSet<Error> Error { get; set; }
        public DbSet<Excepcion> Excepcion { get; set; }
        public DbSet<Modulo> Modulo { get; set; }
        public DbSet<Pagina> Pagina { get; set; }
        public DbSet<Permiso> Permiso { get; set; }
        public DbSet<Proceso> Proceso { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<SubModulo> SubModulo { get; set; }
        public DbSet<EjeIntervencion> EjeIntervencion { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Clase> Clase { get; set; }
        public DbSet<AvancePOTC_Ficha06Integrantes> AvancePOTC_Ficha06Integrantes { get; set; }
        public DbSet<MarcoLogicoTC> MarcoLogicoTC { get; set; }
        public DbSet<AvancePOTC_Ficha03> AvancePOTC_Ficha03 { get; set; }
        public DbSet<AvancePOTC_Ficha02> AvancePOTC_Ficha02 { get; set; }
        public DbSet<PlanOperativoTareaTC> PlanOperativoTareaTC { get; set; }
        public DbSet<Lista> Lista { get; set; }
        public DbSet<ListaDetalle> ListaDetalle { get; set; }
        public DbSet<AvancePOTC_Ficha04> AvancePOTC_Ficha04 { get; set; }
        public DbSet<AvancePOTC_Ficha04Integrantes> AvancePOTC_Ficha04Integrantes { get; set; }
        public DbSet<AvancePOTC_Ficha01> AvancePOTC_Ficha01 { get; set; }
        public DbSet<Participantes> Participantes { get; set; }
        public DbSet<Configuracion> Configuracion { get; set; }
        public DbSet<Persona> Persona { get; set; }
        public DbSet<vPersona> vPersona { get; set; }
        public DbSet<AvancePOTC> AvancePOTC { get; set; }
    }
}
