//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulos
    {
        public Modulos()
        {
            this.ModuloArchivo = new HashSet<ModuloArchivo>();
            this.Sesion = new HashSet<Sesion>();
        }
    
        public int id { get; set; }
        public int configuracionid { get; set; }
        public int moduloid { get; set; }
        public int orden { get; set; }
    
        public virtual ICollection<ModuloArchivo> ModuloArchivo { get; set; }
        public virtual ICollection<Sesion> Sesion { get; set; }
        public virtual Configuracion Configuracion { get; set; }
    }
}
