//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagina
    {
        public Pagina()
        {
            this.Permiso = new HashSet<Permiso>();
        }
    
        public int id { get; set; }
        public int submoduloid { get; set; }
        public string descripcion { get; set; }
        public byte estado { get; set; }
        public byte orden { get; set; }
        public string url { get; set; }
        public string img { get; set; }
        public string main { get; set; }
        public bool aud_anulado { get; set; }
        public long aud_fechareg { get; set; }
        public string aud_usuarioreg { get; set; }
        public string aud_ipreg { get; set; }
        public long aud_fechamod { get; set; }
        public string aud_usuariomod { get; set; }
        public string aud_ipmod { get; set; }
    
        public virtual SubModulo SubModulo { get; set; }
        public virtual ICollection<Permiso> Permiso { get; set; }
    }
}
