//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participantes
    {
        public int id { get; set; }
        public int personaid { get; set; }
        public int claseid { get; set; }
        public Nullable<int> notaentrada { get; set; }
        public Nullable<int> notasalida { get; set; }
    
        public virtual Clase Clase { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
