//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int id { get; set; }
        public int paginaid { get; set; }
        public int rolid { get; set; }
        public bool acceder { get; set; }
        public bool agregar { get; set; }
        public bool modificar { get; set; }
        public bool eliminar { get; set; }
    
        public virtual Pagina Pagina { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
