//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Inscripcion = new HashSet<Inscripcion>();
            this.Participantes = new HashSet<Participantes>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string apellidopaterno { get; set; }
        public string apellidomaterno { get; set; }
        public string nombre { get; set; }
        public Nullable<int> estadocivilid { get; set; }
        public Nullable<int> sexoid { get; set; }
        public int ejeintervencionid { get; set; }
        public Nullable<int> telecentroid { get; set; }
        public string localidad { get; set; }
        public string direccion { get; set; }
        public Nullable<int> gradoinstruccionid { get; set; }
        public string dni { get; set; }
        public Nullable<System.DateTime> fechanacimiento { get; set; }
        public Nullable<int> edad { get; set; }
        public string lugarnacimiento { get; set; }
        public Nullable<int> ocupacionid { get; set; }
        public string ocupacionotro { get; set; }
        public string centrotrabajo { get; set; }
        public string telefono { get; set; }
        public string asociacion { get; set; }
        public string cargoocupa { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string hectareas { get; set; }
        public string observacion { get; set; }
        public Nullable<int> tipocomunidadid { get; set; }
        public Nullable<decimal> tiempoorganizacion { get; set; }
        public Nullable<decimal> tiempotelecentro { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public byte[] foto { get; set; }
        public Nullable<long> fotolength { get; set; }
        public bool aud_anulado { get; set; }
        public long aud_fechareg { get; set; }
        public string aud_usuarioreg { get; set; }
        public string aud_ipreg { get; set; }
        public long aud_fechamod { get; set; }
        public string aud_usuariomod { get; set; }
        public string aud_ipmod { get; set; }
        public string nombre_original { get; set; }
        public Nullable<int> notaentrada { get; set; }
        public Nullable<int> notasalida { get; set; }
	public Nullable<bool> usodatos { get; set; }
    
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
        public virtual ICollection<Participantes> Participantes { get; set; }
    }
}
