//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanOperativoMeta
    {
        public PlanOperativoMeta()
        {
            this.PlanOperativoMetaArchivo = new HashSet<PlanOperativoMetaArchivo>();
            this.AvancePO = new HashSet<AvancePO>();
            this.PlanOperativoMetaAnual = new HashSet<PlanOperativoMetaAnual>();
        }
    
        public int id { get; set; }
        public int poid { get; set; }
        public string codigo { get; set; }
        public string meta { get; set; }
        public decimal cantidad { get; set; }
        public int unidadid { get; set; }
        public string indicador { get; set; }
        public string fuente { get; set; }
        public bool aud_anulado { get; set; }
        public long aud_fechareg { get; set; }
        public string aud_usuarioreg { get; set; }
        public string aud_ipreg { get; set; }
        public long aud_fechamod { get; set; }
        public string aud_usuariomod { get; set; }
        public string aud_ipmod { get; set; }
    
        public virtual ICollection<PlanOperativoMetaArchivo> PlanOperativoMetaArchivo { get; set; }
        public virtual ICollection<AvancePO> AvancePO { get; set; }
        public virtual PlanOperativo PlanOperativo { get; set; }
        public virtual ICollection<PlanOperativoMetaAnual> PlanOperativoMetaAnual { get; set; }
    }
}
