//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanOperativoTareaMetaTC
    {
        public int id { get; set; }
        public int potareaid { get; set; }
        public int anio { get; set; }
        public int ejeintervencionid { get; set; }
        public int telecentro { get; set; }
        public Nullable<decimal> mes1 { get; set; }
        public Nullable<decimal> mes2 { get; set; }
        public Nullable<decimal> mes3 { get; set; }
        public Nullable<decimal> mes4 { get; set; }
        public Nullable<decimal> mes5 { get; set; }
        public Nullable<decimal> mes6 { get; set; }
        public Nullable<decimal> mes7 { get; set; }
        public Nullable<decimal> mes8 { get; set; }
        public Nullable<decimal> mes9 { get; set; }
        public Nullable<decimal> mes10 { get; set; }
        public Nullable<decimal> mes11 { get; set; }
        public Nullable<decimal> mes12 { get; set; }
    
        public virtual PlanOperativoTareaTC PlanOperativoTareaTC { get; set; }
    }
}
