//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanOperativoTareaTC
    {
        public PlanOperativoTareaTC()
        {
            this.PlanOperativoTareaArchivoTC = new HashSet<PlanOperativoTareaArchivoTC>();
            this.PlanOperativoTareaMetaTC = new HashSet<PlanOperativoTareaMetaTC>();
            this.AvancePOTC = new HashSet<AvancePOTC>();
        }
    
        public int id { get; set; }
        public int poid { get; set; }
        public string codigo { get; set; }
        public string tarea { get; set; }
        public string indicador { get; set; }
        public int unidadid { get; set; }
        public string fuente { get; set; }
        public bool ficha1 { get; set; }
        public bool ficha2 { get; set; }
        public bool ficha3 { get; set; }
        public bool ficha4 { get; set; }
        public bool ficha6 { get; set; }
        public bool aud_anulado { get; set; }
        public long aud_fechareg { get; set; }
        public string aud_usuarioreg { get; set; }
        public string aud_ipreg { get; set; }
        public long aud_fechamod { get; set; }
        public string aud_usuariomod { get; set; }
        public string aud_ipmod { get; set; }
    
        public virtual ICollection<PlanOperativoTareaArchivoTC> PlanOperativoTareaArchivoTC { get; set; }
        public virtual ICollection<PlanOperativoTareaMetaTC> PlanOperativoTareaMetaTC { get; set; }
        public virtual PlanOperativoTC PlanOperativoTC { get; set; }
        public virtual ICollection<AvancePOTC> AvancePOTC { get; set; }
    }
}
