//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Excepcion = new HashSet<Excepcion>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string clave { get; set; }
        public string nombre { get; set; }
        public string cargo { get; set; }
        public Nullable<int> telecentro { get; set; }
        public bool admin { get; set; }
        public int rolid { get; set; }
        public bool aud_anulado { get; set; }
        public long aud_fechareg { get; set; }
        public string aud_usuarioreg { get; set; }
        public string aud_ipreg { get; set; }
        public long aud_fechamod { get; set; }
        public string aud_usuariomod { get; set; }
        public string aud_ipmod { get; set; }
        public Nullable<bool> coordinador { get; set; }
    
        public virtual ICollection<Excepcion> Excepcion { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
