//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPersona
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public string apellidopaterno { get; set; }
        public string apellidomaterno { get; set; }
        public string nombre { get; set; }
        public Nullable<int> sexoid { get; set; }
        public string sexo { get; set; }
        public Nullable<int> telecentroid { get; set; }
        public string telecentro { get; set; }
        public int ejeintervencionid { get; set; }
        public string ejeintervencion { get; set; }
        public string localidad { get; set; }
        public string dni { get; set; }
        public Nullable<System.DateTime> fechanacimiento { get; set; }
        public Nullable<int> edad { get; set; }
        public string lugarnacimiento { get; set; }
        public Nullable<int> ocupacionid { get; set; }
        public string ocupacion { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public byte[] foto { get; set; }
        public int fotohash { get; set; }
        public string fotomb { get; set; }
        public int eliminable { get; set; }
    }
}
